#!/bin/sh

set -e


dot_dir=`pwd`

# The url for the git repository to clone oh-my-zsh from.
omz='git@github.com:blinsay/oh-my-zsh.git'

setup_zsh() {
  if [ -d ~/.oh-my-zsh ]
  then
    echo "\033[0;33mYou already have Oh My Zsh installed to ~/.oh-my-zsh.\033[0m"
    echo "For a totally clean install, 'rm -rf ~/.oh-my-zsh ~/.zshrc' and try again"
  else
    # Git clone, but skip the default OMZ install script.
    git clone $omz ~/.oh-my-zsh
    if [ -f ~/.zshrc ] || [ -h ~/.zshrc ]
    then
      mv ~/.zshrc ~/.zshrc.bak
    fi

    # Set the default shell
    if [ "$SHELL" != `which zsh` ]
    then
      chsh -s `which zsh`
    fi

    cp $dot_dir/dot.zshrc ~/.zshrc
  fi
}

update_zshrc() {
  if [ "`md5 -q $dot_dir/dot.zshrc`" != "`md5 -q ~/.zshrc`" ]
  then
    echo "\033[0;32mUpdating zshrc...\033[0m"
    mv ~/.zshrc ~/.zshrc.bak
    cp $dot_dir/dot.zshrc ~/.zshrc
  fi
}

update_gitconfig() {
  echo "\033[0;32mUpdating global gitconfig...\033[0m"
  cp $dot_dir/gitignore_global ~/.gitignore_global
  git config --global core.excludesfile ~/.gitignore_global
}

_welcome_to_hell() {
  echo ''
  echo ''
  echo ''
  echo ''
  echo '\033[0;35m'
  echo ' /$$      /$$ /$$$$$$$$ /$$        /$$$$$$   /$$$$$$  /$$      /$$ /$$$$$$$$'
  echo '| $$  /$ | $$| $$_____/| $$       /$$__  $$ /$$__  $$| $$$    /$$$| $$_____/'
  echo '| $$ /$$$| $$| $$      | $$      | $$  \__/| $$  \ $$| $$$$  /$$$$| $$      '
  echo '| $$/$$ $$ $$| $$$$$   | $$      | $$      | $$  | $$| $$ $$/$$ $$| $$$$$   '
  echo '| $$$$_  $$$$| $$__/   | $$      | $$      | $$  | $$| $$  $$$| $$| $$__/   '
  echo '| $$$/ \  $$$| $$      | $$      | $$    $$| $$  | $$| $$\  $ | $$| $$      '
  echo '| $$/   \  $$| $$$$$$$$| $$$$$$$$|  $$$$$$/|  $$$$$$/| $$ \/  | $$| $$$$$$$$'
  echo '|__/     \__/|________/|________/ \______/  \______/ |__/     |__/|________/'
  echo '                                                                            '
  echo '                                                                            '
  echo '                                                                            '
  echo '                           /$$$$$$$$/$$$$$$                                 '
  echo '                          |__  $$__/$$__  $$                                '
  echo '                             | $$ | $$  \ $$                                '
  echo '                             | $$ | $$  | $$                                '
  echo '                             | $$ | $$  | $$                                '
  echo '                             | $$ | $$  | $$                                '
  echo '                             | $$ |  $$$$$$/                                '
  echo '                             |__/  \______/                                 '
  echo '                                                                            '
  echo '                                                                            '
  echo '                                                                            '
  echo '                      /$$   /$$ /$$$$$$$$ /$$       /$$                     '
  echo '                     | $$  | $$| $$_____/| $$      | $$                     '
  echo '                     | $$  | $$| $$      | $$      | $$                     '
  echo '                     | $$$$$$$$| $$$$$   | $$      | $$                     '
  echo '                     | $$__  $$| $$__/   | $$      | $$                     '
  echo '                     | $$  | $$| $$      | $$      | $$                     '
  echo '                     | $$  | $$| $$$$$$$$| $$$$$$$$| $$$$$$$$               '
  echo '                     |__/  |__/|________/|________/|________/               '
  echo ''
  echo ''
  echo ''
  echo '\033[0m'
}

_hail_satan() {
  echo ''
  echo ''
  echo ''
  echo ''
  echo '\033[0;35m'
  echo ' /$$   /$$  /$$$$$$  /$$$$$$ /$$                 '
  echo '| $$  | $$ /$$__  $$|_  $$_/| $$                 '
  echo '| $$  | $$| $$  \ $$  | $$  | $$                 '
  echo '| $$$$$$$$| $$$$$$$$  | $$  | $$                 '
  echo '| $$__  $$| $$__  $$  | $$  | $$                 '
  echo '| $$  | $$| $$  | $$  | $$  | $$                 '
  echo '| $$  | $$| $$  | $$ /$$$$$$| $$$$$$$$           '
  echo '|__/  |__/|__/  |__/|______/|________/           '
  echo '                                                 '
  echo '                                                 '
  echo '                                                 '
  echo '  /$$$$$$   /$$$$$$  /$$$$$$$$ /$$$$$$  /$$   /$$'
  echo ' /$$__  $$ /$$__  $$|__  $$__//$$__  $$| $$$ | $$'
  echo '| $$  \__/| $$  \ $$   | $$  | $$  \ $$| $$$$| $$'
  echo '|  $$$$$$ | $$$$$$$$   | $$  | $$$$$$$$| $$ $$ $$'
  echo ' \____  $$| $$__  $$   | $$  | $$__  $$| $$  $$$$'
  echo ' /$$  \ $$| $$  | $$   | $$  | $$  | $$| $$\  $$$'
  echo '|  $$$$$$/| $$  | $$   | $$  | $$  | $$| $$ \  $$'
  echo ' \______/ |__/  |__/   |__/  |__/  |__/|__/  \__/'
  echo ''
  echo ''
  echo ''
  echo '\033[0m'
}


case "$1" in
  install)
    echo "\033[0;32mSetting up ZSH...\033[0m"
    setup_zsh
    _welcome_to_hell
    /usr/bin/env zsh
    ;;
  update)
    update_zshrc
    update_gitconfig
    ;;
  *)
    echo "$0 [instal|update]"
esac

_hail_satan


