# Basics
git@github.com:tpope/vim-sensible.git
git@github.com:tpope/vim-fugitive.git
git@github.com:altercation/vim-colors-solarized.git
git@github.com:w0rp/ale.git
git@github.com:tpope/vim-vinegar.git
git@github.com:vim-airline/vim-airline.git
git@github.com:vim-airline/vim-airline-themes.git
git@github.com:tpope/vim-commentary.git

# Clojure
git@github.com:vim-scripts/paredit.vim.git
git@github.com:guns/vim-clojure-static.git
git@github.com:kien/rainbow_parentheses.vim.git
git@github.com:tpope/vim-salve.git
git@github.com:tpope/vim-projectionist.git
git@github.com:tpope/vim-dispatch.git
git@github.com:tpope/vim-fireplace.git
git@github.com:venantius/vim-cljfmt.git

# Dockerfiles
git@github.com:ekalinin/Dockerfile.vim.git

# Elm
git@github.com:ElmCast/elm-vim.git

#Graphql
git@github.com:jparise/vim-graphql.git

# Go
git@github.com:fatih/vim-go.git

# JS
git@github.com:pangloss/vim-javascript.git

# Markdown
git@github.com:tpope/vim-markdown.git

# OpenGL
git@github.com:tikhomirov/vim-glsl.git

# Protobuf
git@github.com:uarun/vim-protobuf.git

# R
git@github.com:jcfaria/Vim-R-plugin.git

# Rust
git@github.com:rust-lang/rust.vim.git
git@github.com:racer-rust/vim-racer.git

# Terraform
git@github.com:hashivim/vim-terraform.git

# Typescript
git@github.com:leafgarland/typescript-vim.git
git@github.com:Quramy/tsuquyomi.git
