# Basics
git://github.com/tpope/vim-sensible.git
git://github.com/altercation/vim-colors-solarized.git
git@github.com:scrooloose/nerdtree.git
git@github.com:scrooloose/syntastic.git
git@github.com:rking/ag.vim.git
git@github.com:tpope/vim-fugitive.git

git@github.com:ctrlpvim/ctrlp.vim.git

# Clojure
git@github.com:vim-scripts/paredit.vim.git
git@github.com:guns/vim-clojure-static.git
git@github.com:kien/rainbow_parentheses.vim.git
git@github.com:tpope/vim-salve.git
git@github.com:tpope/vim-projectionist.git
git@github.com:tpope/vim-dispatch.git
git@github.com:tpope/vim-fireplace.git
git@github.com:venantius/vim-cljfmt.git

# Dockerfiles
git@github.com:ekalinin/Dockerfile.vim.git

# Elm
git@github.com:ElmCast/elm-vim.git

#Graphql
git@github.com:jparise/vim-graphql.git

# Go
git@github.com:fatih/vim-go.git

# JS
git@github.com:pangloss/vim-javascript.git

# Markdown
git@github.com:tpope/vim-markdown.git

# OpenGL
git@github.com:tikhomirov/vim-glsl.git

# R
git@github.com:jcfaria/Vim-R-plugin.git

# Rust
git@github.com:rust-lang/rust.vim.git
git@github.com:racer-rust/vim-racer.git

# Terraform
git@github.com:hashivim/vim-terraform.git
